colorScheme = "blowfish"
defaultAppearance = "light"
autoSwitchAppearance = true
enableSearch = true
enableCodeCopy = true
firebase = { }
fathomAnalytics = { }
verification = { }

defaultBackgroundImage = "web_background.jpg"

[header]
layout = "basic"

[footer]
showCopyright = true
showThemeAttribution = true
showAppearanceSwitcher = true
showScrollToTop = true

[homepage]
layout = "background"  
showRecent = false



[article]
showDate = true
showDateUpdated = false
showAuthor = true
showHero = true
heroStyle = "background"
showBreadcrumbs = true
showDraftLabel = true
showEdit = false
editAppendPath = true
seriesOpened = false
showHeadingAnchors = true
showPagination = true
invertPagination = false
showReadingTime = true
showTableOfContents = true
showTaxonomies = false
showAuthorsBadges = false
showWordCount = true
showSummary = true
sharingLinks = [
  "linkedin",
  "twitter",
  "whatsapp",
  "pinterest",
  "reddit",
  "facebook",
  "email"
]
editURL = ""

[list]
showBreadcrumbs = false
showSummary = true
showTableOfContents = false
showCards = false
groupByYear = true
cardView = false
cardViewScreenWidth = false

[sitemap]
excludedKinds = [ ]

[taxonomy]
showTermCount = true
